cabal-version:      3.0
name:               H-Passworder
version:            0.1.0.0
license:            MIT
license-file:       LICENSE
author:             HıX5eT
maintainer:         emreozabay629@gmail.com
category:           Security
build-type:         Simple

executable H-Passworder
    hs-source-dirs:   app
    main-is:          Main.hs
    build-depends:    base >= 4.14 && < 5,
                      random >= 1.2 && < 1.3
    default-language: Haskell2010